import { Button } from "antd";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useConfirm } from "../components/AntdConfirm/ConfirmContext";
import ConfirmProvider from "../components/AntdConfirm/ConfirmProvider";
import styles from "../styles/Home.module.css";

const MaterialConfirmExample = () => {
  const confirm = useConfirm();
  const handleClick = async () => {
    const result = await confirm({
      title: "Do you want to delete this item?",
      description: "This item will be deleted forever and cannot be undone",
      okButtonText: "Yes",
      cancelButtonText: "No",
    });
    if (result) {
      alert("User confirmed");
    } else {
      alert("User cancelled");
    }
  };
  return (
    <Button type="primary" onClick={handleClick}>
      Open Modal
    </Button>
  );
};

const Home: NextPage = () => {
  return (
    <ConfirmProvider>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.tsx</code>
          </p>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
      <MaterialConfirmExample></MaterialConfirmExample>
    </ConfirmProvider>
  );
};

export default Home;
